### ISSUE TITLE
Cannot host Typesense-Dashboard on HTTPS

### ISSUE THREAD

**Issue by siddharthgaur2590** [bfritscher/typesense-dashboard#24]
Hi Team, I'm keep getting this error: **server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"static","http_port":80.**

Though I have used the Ingress to host my deployed instance on some DNS. Further I've used pc, pvc, deployment, secret, service and ingress ofcourse. Does it only work on port 80?

Also, FYI I'm able to connect it through IP but not through DNS.

CC: @bfritscher Boris Fritscher

Need the urgent solution to self-host the typesense-dashboard on K8s.

**Comment by bfritscher** [comment]
Hi, the image does only serve on port 80 by default. This can be a problem if your cluster requires rootless. You can check caddy doc or even adapt dockerfile to another web server. You can also use the image as a volume only, since the app is a static spa compiled into the image.

Your problems seem more with a wrongly configured ingress and port/service mapping. In standard config ssl is to the ingress which then proxies to internal HTTP service. If you require ssl also on the image you need to extended it. Pull request welcome.

Regards
Boris
